# Generated by Django 5.2.8 on 2025-11-14 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('nif', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_publicacion', models.DateField()),
                ('precio', models.FloatField()),
                ('num_paginas', models.IntegerField()),
                ('genero', models.CharField(choices=[('H', 'Historico'), ('R', 'Romance'), ('A', 'Acción'), ('F', 'Fantasía')], max_length=1)),
                ('idioma', models.CharField(choices=[('ESP', 'Español'), ('EUS', 'Euskera'), ('ENG', 'Ingles')], max_length=3)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appLibreria.autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appLibreria.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libros', models.ManyToManyField(to='appLibreria.libro')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appLibreria.usuario')),
            ],
        ),
    ]
