# Generated by Django 5.2.8 on 2025-11-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLibreria', '0002_alter_carrito_usuario_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
