# Generated by Django 5.2.8 on 2025-11-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLibreria', '0003_libro_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
