# Generated by Django 5.2.8 on 2025-12-17 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLibreria', '0005_remove_carrito_libros_carritoitem'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS Usuarios ("
            "id INTEGER PRIMARY KEY AUTOINCREMENT,"
            "nombre_usuario TEXT UNIQUE NOT NULL,"
            "email_usuario TEXT UNIQUE NOT NULL,"
            "password_hash TEXT NOT NULL);",
            reverse_sql="DROP TABLE IF EXISTS Usuarios;"
        )
    ]
